### ISSUE TITLE
Distributed IO does not track indices right

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#178]
Pilot 1 data (data_reader_candle_pilot1.prototext) on 256 LBANN ranks and with a mini-batch size of 1024. My model prototext sets num_parallel_readers to 0 and uses a model-parallel distributed IO input layer and a reconstruction target layer.

Results in a single rank throwing this exception after the first epoch:
```
**************************************************************************
 This lbann_exception is about to be thrown:/usr/workspace/wsa/dryden1/lbann2/src/data_readers/data_reader.cpp 234 :: generic data reader update error: the epoch is complete, but not all of the data has been used -
- current pos = 146432 and there are 146635 indices

 Am now attemptting to print the stack trace ...
**************************************************************************
rank: 143 :: lbann::stack_trace::print_stack_trace()
rank: 143 :: lbann::stack_trace::print_lbann_exception_stack_trace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
rank: 143 :: lbann::lbann_exception::lbann_exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
rank: 143 :: lbann::generic_data_reader::update(bool, bool)
rank: 143 :: lbann::distributed_io_buffer::is_data_set_processed(lbann::generic_data_reader*, execution_mode)
rank: 143 :: lbann::Layer::update()
rank: 143 :: lbann::model::evaluate_mini_batch(execution_mode)
rank: 143 :: lbann::model::evaluate(execution_mode)
rank: 143 :: lbann::model::train(int)
rank: 143 :: dli_sname == NULL for: 0x40401c backtrace message was:      /usr/workspace/wsa/dryden1/lbann2/./build/gnu.catalyst.llnl.gov/install/bin/lbann() [0x40401c]
rank: 143 :: demangling failed for: __libc_start_main
rank: 143 :: dli_sname == NULL for: 0x404634 backtrace message was:      /usr/workspace/wsa/dryden1/lbann2/./build/gnu.catalyst.llnl.gov/install/bin/lbann() [0x404634]
```

**Comment by ndryden** [comment]
Assigned @bvanessen but feel free to reassign if there's someone better suited.

**Comment by bvanessen** [comment]
Can you please attach the command line that was used to start the run.

**Comment by ndryden** [comment]
`/usr/workspace/wsa/dryden1/lbann2/./build/gnu.catalyst.llnl.gov/install/bin/lbann --model=pilot1b3_snn_autoencoder.prototext --reader=model_zoo/data_readers/data_reader_candle_pilot1.prototext --optimizer=model_zoo/optimizers/opt_adam.prototext`

I'll send you the SNN autoencoder prototext.

**Comment by davidHysom** [comment]
This should be fixed after my bugfix this morning, but I don't want to close this issue until someone else verifies.

**Comment by bvanessen** [comment]
I have been able to reproduce this on Ray with the current head of the develop branch.  I will continue to investigate:
bash-4.2$ mpirun -np 160 ./build/ray.llnl.gov/lbann/build/model_zoo/lbann --model=model_zoo/models/autoencoder_candle_pilot1/pilot1b3_snn_autoencoder.prototext --reader=model_zoo/data_readers/data_reader_candle_pilot1.prototext --optimizer=model_zoo/optimizers/opt_adam.prototext

Model 0 training epoch 0 mini-batch time statistics : 0.108335s mean, 27.3742s max, 0.0269317s min, 0.762863s stdev

**************************************************************************
 This lbann_exception is about to be thrown:/g/g19/vanessen/DeepLearning/lbann.git/src/data_readers/data_reader.cpp 252 :: generic data reader update error: the epoch is complete, but not all of the data has been used -- current pos = 146432 and there are 146635 indices

 Am now attemptting to print the stack trace ...
**************************************************************************

**Comment by davidHysom** [comment]
This should be fixed after my push this morning. If someone can verify, this issue can be closed.

**Comment by ndryden** [comment]
Appears to be fixed. Thanks, Dave!

**Comment by bvanessen** [comment]
I am running into this bug right now, so I don't think that it is fixed.

**Comment by ndryden** [comment]
Okay, concur, I can still reproduce it. Looks like it went away when I had the validation percent set to 0 in the data reader prototext. Perhaps there's an issue with the copy constructor or setting up the validation data reader?

**Comment by davidHysom** [comment]
Please give, mail or push the model prototext file so I can reproduce.

**Comment by ndryden** [comment]
Done! I think Brian has an idea of where it's coming from (an incorrect calculation on one process).

**Comment by bvanessen** [comment]
Dave I have pinpointed the problem just need to get the right fix.


Brian C. Van Essen

vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>

(w) 925-422-9300

(c) 925-290-5470

---

Sent from my iPhone

On Feb 1, 2018, at 5:34 AM, Nikoli Dryden <notifications@github.com<mailto:notifications@github.com>> wrote:


Done! I think Brian has an idea of where it's coming from (an incorrect calculation on one process).

**Comment by davidHysom** [comment]
With a fresh checkout and build this morning, this problem did not show up on surface.  
srun --nodes 4 -n 16 build/gnu.surface.llnl.gov/install/bin/lbann --model=pilot1b3_snn_autoencoder.prototext --reader=model_zoo/data_readers/data_reader_candle_pilot1.prototext --optimizer=model_zoo/optimizers/opt_adam.prototext --stack_trace_to_file

**Comment by bvanessen** [comment]
I believe that the problem manifests when you have more ranks that legal parallel readers.  I am encountering it at 160 ranks with a max of 144 parallel readers on the validation dataset.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by bvanessen** [comment]
I have fixed the bug that was causing this in e9ebf3b84cf09b1cf9ba551f37645d7b27e0df74.
