### ISSUE TITLE
README.md out of date

### ISSUE THREAD

**Issue by mcneish1** [LLNL/lbann#192]
In the Verifying LBANN on LC section, for example,
srun -n12 build/catalyst.llnl.gov/model_zoo/lbann [...]
should be
srun -n12 build/gnu.catalyst.llnl.gov/lbann/build/model_zoo/lbann [...]

In the Cmake (Non LC or OSX Systems/Script alternative) section,
cmake ../.. per the instructions is one directory below the lbann git directory, where there shouldn't be a relevant CMakeLists

There are probably other places it's fallen behind, those are the two that stuck out

**Comment by DylanMcKinney** [comment]
I addressed this with #244. Nothing else was very obviously wrong. The readme could probably use some touching up in other places, but for right now I am closing this.

**Comment by mxmlnkn** [comment]
I vote to reopen.

Even the `cmake ../..``mentioned by @mcneish1 still exists in [this](https://github.com/LLNL/lbann/#cmake-non-lc-or-osx-systemsscript-alternative) section. Furthermore the formatting is wrong but that is fixed with #859

However there are other problems in that section (I didn't look over the others much):

 - Cmake -> CMake
 - `cmake ../..` -> `cmake ..`
 - Hydrogen dependency missing (running cmake gives: `Could not find a package configuration file provided by "Hydrogen"`, no link to hydrogen
 - link to Elemental ( https://software.llnl.gov/lbann/elemental.html ) is outdated (404) -> use http://libelemental.org/

 - Also, [this](https://github.com/LLNL/lbann/blob/develop/docs/BuildingLBANN.md#building--installing-lbann-as-a-user) is empty even thought hat was the first place I looked when trying to build LBANN.

**Comment by mcneish1** [comment]
@bvanessen
